### ISSUE TITLE
Rofi version?

### ISSUE THREAD

**Issue by galou** [niraj998/Rofi-Scripts#1]
Hi,

thanks for providing your script to the community! I especially the Wifi script and wanted to give it a try.

I may have a problem with my version of rofi (1.5.4) but got an error:
```
[...] prompt.rasi [...]
[...] syntax error [...] expected property separator
[...] line 11 column 12 to line 11 column 14 [...]
```

Thanks for your help!

**Comment by niraj998** [comment]
I'm using 1.7.3
can you update to latest version and give it another try ?

**Comment by niraj998** [comment]
The Line mentioned in the Error are setting theme for file browser, plugin which was integrated into rofi in 1.6.1 release 

(https://github.com/davatorium/rofi/releases/tag/1.6.1)
Thank you for using my scripts,
Please give it another try when you update rofi.
I've updated README to use latest rofi
I'm closing this issue for now.
if you still get error after update feel free to create issue.

Thank you

**Comment by galou** [comment]
I didn't manage to compile the latest rofi but thanks to your help I removed the configuration that made causing the issue. Thanks!

**Comment by niraj998** [comment]
Happy to see it work,
One more thing you could do if you want  or get error is, I have defined path to rofi configuration files to use at the top of each script you can replace those with your own configuration files. scripts should still work, theme you can create your own.
